name: build and test feature branch  
on:
  pull_request: # el workflow se ejecuta cuando se crea un pull request
    branches: [develop] # el workflow se ejecuta cuando se crea un pull request a la rama develop
    types: [opened, reopened]
jobs: 
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} #descarga el codigo de la rama que disparo el evento

      - name: pull and checkout from git repository
        run: |
         echo "Pulling and checking out from git repository..."

      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository # Path to cache
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Cache key
          restore-keys: |
            ${{ runner.os }}-maven- # Prefix for cache key
      
      - name: Build with Maven
        run: |
          mvn clean test package
          echo "build with maven"

#######################################################
# Automatic merge to develop branch
#######################################################
  merge-feature-into-develop:
    runs-on: ubuntu-latest
    needs: build-feature  #depends on the build-feature job
    if: ${{ success() }}  #only run if the build-feature job was successful
    #[For a specific job, you can use jobs.<job_id>.permissions to modify the default permissions granted to the GITHUB_TOKEN](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)
    permissions:
      contents: write
      pull-requests: write
    steps:
      #######################################################
      # 1- Dowload source code
      #Only a single commit is fetched by default, for the ref/SHA that triggered the workflow, Set fetch-depth: 0 to fetch all history for all branches and tags
      #######################################################
      - uses: actions/checkout@v3
        with:
          #Dowload the code from destination branch (develop)
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      # ########################################################
      # # 2- Merge to development branch
      # ########################################################
      - name: Merge to development branch
        if: ${{ success() }}
        run: |
          git config --global user.email "EMAIL-OF-WORKFLOW@USER"
          git config --global user.name "WORKFLOW-USER" 
          #Using -m "mesage" on merge command ins mandatori here in order to avoid open a text editor to write a commit message
          git merge --no-ff --verbose origin/${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"
          #is important agg -m "mesage" on merge command in order to avoid open a text editor to write a commit message

      ########################################################
      # 3- Push changes after merge
      ##########################################################

      - name: Push changes after merge
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.base_ref }}

      ##################################################### 
      # 4- call publish-jar-as-artifact
      #####################################################
      - name: trigger deploy artifact
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: publish-artifact-event          
          client-payload: '{ "base_branch": "${{ github.base_ref }}" }'
